import keyMirror from "keymirror";

export default keyMirror({
	ATLAS                  : null,
	PARENTS                : null,
	FIRST_CHILDS           : null,
	INFO                   : null,
	GRILLE_10              : null,
	BROTHERS               : null,
	PHOTO                  : null,
	MONOGRAPHIES           : null,
	PHENOLOGIE             : null,
	UPDATE_TITLE           : null,
	NOT_PARENTS            : null,
	NOT_FIRST_CHILDS       : null,
	NOT_INFO               : null,
	NOT_GRILLE_10          : null,
	NOT_BROTHERS           : null,
	NOT_PHOTO              : null,
	NOT_MONOGRAPHIES       : null,
	NOT_CHILDS             : null,
	EXPLORE_SUB            : null,
	EXPLORE_SUP            : null,
	EXPLORE_CHILDS         : null,
	EXPLORE_FIRST_CHILDS   : null,
	START_REQUEST_EXPLORER : null,
	END_REQUEST_EXPLORER   : null,
	SEARCH_CHILDS          : null,
	REQUEST_SEARCH_PENDING : null,
	END_REQUEST_PENDING    : null,
	RESET_SEARCH_CHILDS    : null,
	NOT_SEARCH_CHILDS      : null,
	UNAUTHORIZED           : null,
	ACCESS_TOKEN           : null
});
